In [1]:
%%time

UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [3]:
import sys
sys.path.append('..')

#from torchmetrics import BLEUScore, WordErrorRate

import torch

from math import log, exp, e

import numpy as np
from src.utils import Metrics
from src import DataLoader
from src import Model
from data.dataset import MTDataset

/Users/lukas/anaconda3/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [21]:
model = torch.load('../logs/final_model_1.0000/checkpoints/model_1.pt')
input_names = ['German Source', 'English Target']
output_names = ['English Token']
args =  (torch.randint(1,200,(128,7)),torch.randint(1,200,(128,3)))
torch.onnx.export(model,args,'FFModel.onnx', input_names=input_names, output_names=output_names)

## Torch dataset

In [3]:
model = Model(5000, window=2)

In [4]:
batch1 = torch.randint(0,10,(3,5))
batch2 = torch.randint(0,10,(3,2))
model(batch1,batch2)

tensor([[4, 0, 4, 5, 6],
        [5, 1, 3, 5, 5],
        [3, 2, 6, 0, 2]])
tensor([[6, 9],
        [0, 7],
        [1, 3]])
torch.Size([3, 5])
torch.Size([3, 2])
torch.Size([3, 5, 2048])
torch.Size([3, 2, 2048])
torch.Size([3, 10240])
torch.Size([3, 1024])
torch.Size([3, 4096])
torch.Size([3, 1024])
torch.Size([3, 2048])
torch.Size([3, 1024])
torch.Size([3, 5000])


tensor([[ 0.8297,  0.0507, -0.1398,  ..., -0.1203,  0.0931, -0.1493],
        [ 0.1378,  0.1286,  0.4216,  ...,  0.4917,  0.0968, -0.1690],
        [ 0.1338, -0.1661, -0.1155,  ...,  0.0191,  0.0929, -0.1675]],
       grad_fn=<GeluBackward0>)

In [ ]:
s = torch.tensor([1,2,4,3,1])
t = torch.tensor([1,3])
model(s,t)

torch.Size([5])
torch.Size([2])
torch.Size([5, 2048])
torch.Size([2, 2048])
torch.Size([10240])
torch.Size([1024])
torch.Size([4096])
torch.Size([1024])
torch.Size([2048])
torch.Size([1024])
torch.Size([5000])


/Users/lukas/Machine Translation/machine-translation/notebooks/../src/models/model.py:53: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  z = self.softmax(z)


tensor([ 0.1057, -0.1500,  0.4522,  ...,  0.3500, -0.0410, -0.0478],
       grad_fn=<GeluBackward0>)

In [ ]:
metrics.bleu_score(3,h1_tokens,ref_tokens)

0.031536712281812374

In [ ]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = [(i,j) for i,j in zip(a,b)]
print(c)

[([1, 2], [5, 6]), ([3, 4], [7, 8])]


In [ ]:
bscore = BLEUScore(4)

bscore([data_loader_h1.load_data()],[[data_loader_ref.load_data()]])

tensor(0.5428)

In [ ]:
h1 = data_loader_h1.tokenize(mode="lines_words")
ref = data_loader_ref.tokenize(mode="lines_words")
metrics.bleu_score(4,h1,ref)


0.4850221157121662

## WER Score


### Hypothesis 1

In [ ]:
metrics.WER(h1_sentences, ref_sentences)

0.3644912405408207

In [ ]:
WER1 = WordErrorRate()
WER1.update(preds=h1_sentences, target=ref_sentences)
WER1.compute()

tensor(0.3645)

### Hypothesis 2


In [ ]:
metrics.WER(h2_sentences, ref_sentences)

0.37188087727871816

In [ ]:
WER2 = WordErrorRate()
WER2.update(preds=h2_sentences, target=ref_sentences)
WER2.compute()

tensor(0.3719)

### Hypothesis 3

In [ ]:
metrics.WER(h3_sentences, ref_sentences)

0.6282968294163815

In [ ]:
WER3 = WordErrorRate()
WER3.update(preds=h3_sentences, target=ref_sentences)
WER3.compute()

tensor(0.6283)

## PER Score

### Hypothesis 1

In [ ]:
metrics.PER(h1_sentences, ref_sentences)

0.25061086676440536

### Hypothesis 2

In [ ]:
metrics.PER(h2_sentences, ref_sentences)

0.2557643609222977

### Hypothesis 3

In [ ]:
metrics.PER(h3_sentences, ref_sentences)

0.4657988656389296

## BLEU Score